Repository GoogleContainerTools/jib, pull requests merged in 2018-07, with the labels that each got.

#487 Changes wording "native" to "daemonless".
  README.md
Labels: documentation

#491 Moves docs-unreleased/ to docs/ and adds Google Analytics to docs site.
  docs-unreleased/README.md
  docs-unreleased/config.yml
  docs-unreleased/index.md
  docs/_config.yml
  docs/configure-gcp-credentials.md
  docs/v0.1.1/jib-gradle-plugin.md
  docs/v0.1.7/jib-maven-plugin.md
Labels: documentation

#501 Adds dockerBuild to quickstart.
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: documentation

#496 Adds metadata to plugin JARs.
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-gradle-plugin/build.gradle
  jib-maven-plugin/pom.xml
Labels: P0

#502 Proposal: Build Tarball to Filesystem
  proposals/build_tarball.md
Labels: proposal

#508 Changes cache metadata to take many layer entries instead of just one.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheWriter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/json/CacheMetadataLayerPropertiesObjectTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/json/CacheMetadataTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheFilesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/PlatformSpecificMetadataJson.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/json/CacheMetadataTemplateTest.java
  jib-core/src/test/resources/cache/metadata-v2.json
  jib-core/src/test/resources/json/metadata-v2.json
  jib-core/src/test/resources/json/metadata_windows-v2.json
Labels: P0

#549 Fixes using base image from registry that requires token authentication.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticators.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryUnauthorizedException.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: P0

#554 Updates version to v0.9.4.
  README.md
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: documentation

#562 Builds extra layer with contents of src/main/jib.
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
  jib-gradle-plugin/src/integration-test/resources/projects/simple/src/main/jib/bar/cat
  jib-gradle-plugin/src/integration-test/resources/projects/simple/src/main/jib/foo
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
Labels: jib-gradle-plugin

#565 Builds extra layer with contents of src/main/jib.
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
  jib-maven-plugin/src/test/resources/projects/simple/src/main/jib/bar/cat
  jib-maven-plugin/src/test/resources/projects/simple/src/main/jib/foo
Labels: jib-maven-plugin

#572 Passes allowHttp to RegistryAuthenticator.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticators.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: P0

#587 Updates CONTRIBUTING with notice about integration testing.
  CONTRIBUTING.md
Labels: documentation

#610 Links to Jib as a library for Java issue in README.
  README.md
Labels: documentation

#611 Adds link to blog post in README.
  README.md
Labels: documentation

#617 Adds twitter badge for easy sharing.
  README.md
Labels: documentation

#616 Adds ways to get involved.
  README.md
Labels: documentation

#621 Changes Upcoming Features section to be more sustainable.
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: documentation

#618 Add instructions for self signed certicate
  docs/self_sign_cert.md
Labels: documentation

#649 Adds note about reading CONTRIBUTING.
  README.md
Labels: documentation

#652 Document alternative trust-store option for self-signed certificates
  docs/self_sign_cert-kse-import.png
  docs/self_sign_cert.md
Labels: documentation

#655 Add instructions for building & testing/debugging locally
  CONTRIBUTING.md
  build.sh
Labels: documentation

#666 Move FAQ to docs/ folder
  README.md
  docs/faq.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: documentation

#679 Update FAQ with new features, how to run image, and how to parameterize
  docs/faq.md
Labels: documentation

#688 Creates PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#645 Add SpringBoot application demo for using Jib
  examples/README.md
  examples/spring-boot-draft/README.md
  examples/spring-boot-draft/build.gradle
  examples/spring-boot-draft/gradle.properties
  examples/spring-boot-draft/pom.xml
  examples/spring-boot-draft/settings.gradle
  examples/spring-boot-draft/settings.xml
  examples/spring-boot-draft/src/main/java/com/example/jib/JibApplication.java
  examples/spring-boot-draft/src/main/resources/application.properties
  examples/spring-boot-draft/src/test/java/com/example/jib/JibApplicationTests.java
Labels: documentation
