Repository GoogleContainerTools/jib, pull requests merged in 2018-09, with the labels that each got.

#921 Adds JibEvent, JibEventType, and EventHandlers.
  jib-core/src/main/java/com/google/cloud/tools/jib/event/EventHandlers.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEvent.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEventType.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/EventHandlersTest.java
Labels: cla: yes

#930 Add plugin configuration for environment variables
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/resources/sampleDockerfile
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
  jib-maven-plugin/src/test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
Labels: cla: yes

#932 Improve the error message when pushing to a registry that does not support v2-2
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Labels: cla: yes

#938 Create helper for parsing an error code from error response
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobChecker.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ErrorResponseUtil.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/ErrorResponseUtilTest.java
Labels: cla: yes

#941 Fix ManifestPusherTest warnings
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Labels: cla: yes

#935 Consolidate tool name usage
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
Labels: cla: yes

#944 Report registry and image on RegistryAuthenticationFailedException
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticationFailedException.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticationFailedExceptionTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
Labels: cla: yes

#945 Lower verbosity of insecure registry failover
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
Labels: cla: yes

#951 Restart Docker for Mac to fix clock skew in VM
  kokoro/continuous.sh
Labels: cla: yes

#879 Adds DefaultCacheStorage#write.
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/FileOperations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriter.java
  jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/FileOperationsTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFilesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriterTest.java
Labels: cla: yes

#917 Preparation for Gradle WAR support
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/resources/exploded-war/file
  jib-core/src/test/resources/sampleDockerfile
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
Labels: cla: yes

#898 Adds DefaultCacheStorage#listDigests.
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheCorruptedException.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriter.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReaderTest.java
Labels: cla: yes

#963 Adds additional tags to BuildConfiguration.
  jib-core/src/main/java/com/google/cloud/tools/jib/JibLogger.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
Labels: cla: yes

#968 Pushes to the additional tags.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
Labels: cla: yes

#960 Changes LayerEntry to be more like TarArchiveEntry.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/json/CacheMetadataLayerPropertiesObjectTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/json/CacheMetadataTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/LayerConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/MainClassFinder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheFilesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/PlatformSpecificMetadataJson.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/json/CacheMetadataTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/LayerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/MainClassFinderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-core/src/test/resources/cache/metadata-v3.json
  jib-core/src/test/resources/json/metadata-v3.json
  jib-core/src/test/resources/json/metadata_windows-v3.json
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
Labels: cla: yes

#972 Define system property names in one class
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
  jib-core/src/main/java/com/google/cloud/tools/jib/global/JibSystemProperties.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
  jib-core/src/test/java/com/google/cloud/tools/jib/global/JibSystemPropertiesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Labels: cla: yes

#901 Adds DefaultCacheStorage#retrieve.
  jib-core/src/main/java/com/google/cloud/tools/jib/image/DescriptorDigest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheCorruptedException.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReader.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheEntryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFilesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReaderTest.java
Labels: cla: yes

#878 Proposal RFC: New cache mechanism
  proposals/cache_v2.md
Labels: cla: yes, proposal

#909 Proposal RFC: Emit events from Jib Core
  proposals/events.md
Labels: cla: yes, proposal

#947 Adds Jib and JibContainerBuilder.
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Jib.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/LayerConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/Port.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/ExposedPortsParser.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/ContainerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/PortTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/ExposedPortsParserTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
Labels: cla: yes

#983 Builds to Docker daemon with additional tags.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
Labels: cla: yes

#959 Add in _skaffold-files _skaffold-package-goals
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/PackageGoalsMojo.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/TestPlugin.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/TestProject.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/PackageGoalsMojoTest.java
  jib-maven-plugin/src/test/resources/projects/multi/complex-service/pom.xml
  jib-maven-plugin/src/test/resources/projects/multi/complex-service/src/main/extra-resources-1/resource1.txt
  jib-maven-plugin/src/test/resources/projects/multi/complex-service/src/main/extra-resources-2/resource2.txt
  jib-maven-plugin/src/test/resources/projects/multi/complex-service/src/main/java/com/test/HelloWorld.java
  jib-maven-plugin/src/test/resources/projects/multi/lib/pom.xml
  jib-maven-plugin/src/test/resources/projects/multi/lib/src/main/java/com/lib/Lib.java
  jib-maven-plugin/src/test/resources/projects/multi/lib/src/test/java/com/lib/LibTest.java
  jib-maven-plugin/src/test/resources/projects/multi/pom.xml
  jib-maven-plugin/src/test/resources/projects/multi/simple-service/pom.xml
  jib-maven-plugin/src/test/resources/projects/multi/simple-service/src/main/java/com/test/HelloWorld.java
Labels: cla: yes

#976 Serializes LayerEntry in unix path form.
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/json/CacheMetadataLayerPropertiesObjectTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/PlatformSpecificMetadataJson.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/json/CacheMetadataTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/resources/cache/metadata-v3.json
  jib-core/src/test/resources/json/metadata-v3.json
  jib-core/src/test/resources/json/metadata_windows-v3.json
Labels: cla: yes

#986 List cached layer digests as Set
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReader.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReaderTest.java
Labels: cla: yes

#982 Logs additional tags.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
Labels: cla: yes

#989 jib-maven-plugin Typo
  jib-maven-plugin/README.md
Labels: cla: yes

#952 Adds RegistryImage, DockerDaemonImage, and TarImage.
  jib-core/src/main/java/com/google/cloud/tools/jib/api/DockerDaemonImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/TarImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/Credential.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/CredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/credentials/CredentialTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Labels: P0, cla: yes

#955 Adds Containerizer.
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/DockerDaemonImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/TarImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/TargetImage.java
Labels: cla: yes

#996 Adds SourceImage and has Jib#from also take RegistryImage.
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Jib.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/SourceImage.java
Labels: cla: yes

#1003 Wait until Docker daemon is ready
  kokoro/continuous.sh
Labels: cla: yes

#995 Adds AbsoluteUnixPath to represent Unix paths in absolute form.
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/AbsoluteUnixPath.java
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/RelativeUnixPath.java
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/UnixPathParser.java
  jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/AbsoluteUnixPathTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/RelativeUnixPathTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/UnixPathParserTest.java
Labels: cla: yes

#984 Add container.appRoot config parameter
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/resources/sampleDockerfile
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/README.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Labels: cla: yes

#1006 Wait until local registry is ready when setting it up in integration tests
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
Labels: cla: yes

#1016 Delete containers after run in integration tests
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
Labels: cla: yes

#1015 Add "format" target
  build.sh
Labels: cla: yes

#1012 Use AbsoluteUnixPath for container.appRoot propagation
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/resources/sampleDockerfile
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Labels: cla: yes

#1014 Changes LayerEntry#extractionPath to use AbsoluteUnixPath.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/LayerConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/AbsoluteUnixPath.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/LayerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/AbsoluteUnixPathTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
Labels: cla: yes

#975 Adds Cache with initial method for fetching a cache entry by layer entries.
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/json/JsonTemplateMapper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/json/ListOfJsonTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/LayerEntriesSelector.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/LayerEntriesSelectorTest.java
Labels: cla: yes

#1017 Keep duplicate layers to match history
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageLayers.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageLayersTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1019 Fixes broken compilation caused by merging #1014 and #975.
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/LayerEntriesSelector.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/LayerEntriesSelectorTest.java
Labels: cla: yes

#978 Adds to.tags configuration for Gradle.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/empty/build.gradle
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ImageParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TargetImageParameters.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1026 Adds to.tags configuration for Maven.
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/resources/projects/empty/pom.xml
Labels: cla: yes

#1028 Parallelizes pushing to multiple tags.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
Labels: cla: yes

#971 Replaces JibLogger with EventEmitter in RetrieveRegistryCredentialsStep.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/Timer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/TimerEventEmitter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/DefaultEventEmitter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/EventEmitter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEventType.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/events/LogEvent.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/events/TimerEvent.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/TimerEventEmitterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/TimerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/DefaultEventEmitterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/events/LogEventTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleJibLogger.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/LogEventHandler.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/LogEventHandler.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/TimerEventHandler.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/TimerEventHandlerTest.java
Labels: cla: yes

#1022 Finishes implementing new Cache.
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheWrite.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheWrite.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/CacheWriteTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriterTest.java
Labels: cla: yes

#1023 Remove ListOfJsonTemplate class
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageToTarballTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/json/DockerLoadManifestEntryTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/json/JsonTemplateMapper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/json/ListOfJsonTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/LayerEntriesSelector.java
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/ImageToTarballTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/json/DockerLoadManifestTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/json/JsonTemplateMapperTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/LayerEntriesSelectorTest.java
  jib-core/src/test/resources/json/basic_list.json
Labels: cla: yes

#1021 Add _jibSkaffoldFiles task to gradle plugin
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/FilesTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TestProject.java
  jib-gradle-plugin/src/test/resources/projects/multi-service/build.gradle
  jib-gradle-plugin/src/test/resources/projects/multi-service/complex-service/build.gradle
  jib-gradle-plugin/src/test/resources/projects/multi-service/complex-service/src/main/extra-resources-1/resource1.txt
  jib-gradle-plugin/src/test/resources/projects/multi-service/complex-service/src/main/extra-resources-2/resource2.txt
  jib-gradle-plugin/src/test/resources/projects/multi-service/complex-service/src/main/java/com/test/HelloWorld.java
  jib-gradle-plugin/src/test/resources/projects/multi-service/complex-service/src/main/other-jib/extra-file
  jib-gradle-plugin/src/test/resources/projects/multi-service/gradle.properties
  jib-gradle-plugin/src/test/resources/projects/multi-service/lib/build.gradle
  jib-gradle-plugin/src/test/resources/projects/multi-service/lib/src/main/java/com/lib/Lib.java
  jib-gradle-plugin/src/test/resources/projects/multi-service/lib/src/main/resources/hi.txt
  jib-gradle-plugin/src/test/resources/projects/multi-service/lib/src/test/java/com/lib/LibTest.java
  jib-gradle-plugin/src/test/resources/projects/multi-service/settings.gradle
  jib-gradle-plugin/src/test/resources/projects/multi-service/simple-service/build.gradle
  jib-gradle-plugin/src/test/resources/projects/multi-service/simple-service/src/main/java/com/test/HelloWorld.java
  jib-gradle-plugin/src/test/resources/projects/simple/build.gradle
  jib-gradle-plugin/src/test/resources/projects/simple/libs/dependency-1.0.0.jar
  jib-gradle-plugin/src/test/resources/projects/simple/src/main/custom-extra-dir/bar/cat
  jib-gradle-plugin/src/test/resources/projects/simple/src/main/custom-extra-dir/foo
  jib-gradle-plugin/src/test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
  jib-gradle-plugin/src/test/resources/projects/simple/src/main/resources/world
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoTest.java
Labels: cla: yes

#1032 Use AbsoluteUnixPath for LayerEntry.getAbsoluteSourceFileString()
  jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
Labels: cla: yes

#1039 Gradle release v0.9.11
  jib-gradle-plugin/gradle.properties
Labels: cla: yes

#1040 Maven release v0.9.11
  jib-maven-plugin/pom.xml
Labels: cla: yes

#1034 Start replacing JibLogger calls with Events
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/EmptyJibLogger.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/FinalizingStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/events/LogEvent.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/MainClassFinder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/ExposedPortsParserTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/MainClassFinderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/LogEventHandler.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
Labels: cla: yes

#936 Update documentation for 0.9.11
  CONTRIBUTING.md
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  examples/micronaut/build.gradle
  examples/multi-module/build.gradle
  examples/multi-module/pom.xml
  examples/spring-boot-draft/build.gradle
  examples/spring-boot-draft/pom.xml
  examples/spring-boot-kubernetes/build.gradle
  examples/spring-boot-kubernetes/pom.xml
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/README.md
Labels: cla: yes

#1045 Remove deprecated parameters
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
Labels: cla: yes

#1037 Stores temporary cache files under cache directory.
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriter.java
  jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFilesTest.java
Labels: cla: yes

#1048 Remove JibLogger
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/JibLogger.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/TestJibLogger.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleJibLogger.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenJibLogger.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1052 Remove recursion from files task
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTask.java
Labels: cla: yes

#1046 Changes CacheWrite into UncompressedCacheWrite and adds ability to write compressed layer blob.
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/UncompressedCacheWrite.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/CacheWriteTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriterTest.java
Labels: cla: yes

#1049 New JavaLayerConfiguration API for more flexibility
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/resources/random-contents/file1
  jib-core/src/test/resources/random-contents/file2
  jib-core/src/test/resources/random-contents/sub-directory/file3
  jib-core/src/test/resources/random-contents/sub-directory/file4
  jib-core/src/test/resources/random-contents/sub-directory/leaf/file5
  jib-core/src/test/resources/random-contents/sub-directory/leaf/file6
  jib-core/src/test/resources/sampleDockerfile
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
Labels: cla: yes

#1058 Remove sorting / add resources directory directly
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
Labels: cla: yes

#1057 Archives Proposal: Improved cache mechanism
  proposals/archives/cache_v2.md
Labels: cla: yes

#1056 Renames ncache to cache.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheCorruptedException.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LastModifiedTimeMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/UncompressedCacheWrite.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheEntryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageFilesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LastModifiedTimeMetadataTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
Labels: cla: yes

#987 Proposal RFC: Jib Core as a library for Java
  proposals/jib_core_library.md
Labels: cla: yes

#1064 Fix docker error output not being captured
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
Labels: cla: yes

#1066 Add jib version to layer history
  jib-core/src/main/java/com/google/cloud/tools/jib/ProjectInfo.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
Labels: cla: yes

#1062 Construct correct classes and resources layers for Maven builds
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
Labels: cla: yes
