Repository GoogleContainerTools/jib, pull requests merged in 2018-10, with the labels that each got.

#923 Proposal War support with Gradle
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/resources/sampleDockerfile
  jib-core/src/test/resources/webappSampleDockerfile
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExplodedWarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/META-INF/context.xml
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/Test.jsp
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/WEB-INF/classes/HelloWorld.class
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/WEB-INF/classes/package/Other.class
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/WEB-INF/classes/package/test.properties
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/WEB-INF/lib/dependency-1.0.0.jar
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/WEB-INF/lib/dependencyX-1.0.0-SNAPSHOT.jar
  jib-gradle-plugin/src/test/resources/webapp/jib-exploded-war/WEB-INF/web.xml
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
Labels: cla: yes

#1072 Minor cleanups after merging WAR Gradle support contribution
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/resources/webAppSampleDockerfile
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExplodedWarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
Labels: cla: yes

#1075 Removes CacheConfiguration in favor of setting directories directly on BuildConfiguration.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/CacheConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/CacheConfigurationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
Labels: cla: yes

#1077 Check if WEB-INF, WEB-INF/lib, and WEB-INF/classes exist
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
Labels: cla: yes

#1078 Makes BuildSteps#run return the built image digest.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Labels: cla: yes

#1080 Add system properties for remaining maven config
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Labels: cla: yes

#1084 Makes Docker executable configurable.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
Labels: cla: yes

#1086 Cleanup JibExtension
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1061 Fix to/from closure type in JibExtension
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ImageParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TargetImageParameters.java
Labels: cla: yes

#1087 Add system properties for gradle config
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TargetImageParameters.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
Labels: cla: yes

#1092 Add FAQ for how to set up file system structure with copy-resources
  docs/faq.md
Labels: cla: yes

#1068 Maven War support
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/test/resources/webapp/final-name/META-INF/context.xml
  jib-maven-plugin/src/test/resources/webapp/final-name/Test.jsp
  jib-maven-plugin/src/test/resources/webapp/final-name/WEB-INF/classes/HelloWorld.class
  jib-maven-plugin/src/test/resources/webapp/final-name/WEB-INF/classes/package/Other.class
  jib-maven-plugin/src/test/resources/webapp/final-name/WEB-INF/classes/package/test.properties
  jib-maven-plugin/src/test/resources/webapp/final-name/WEB-INF/lib/dependency-1.0.0.jar
  jib-maven-plugin/src/test/resources/webapp/final-name/WEB-INF/lib/dependencyX-1.0.0-SNAPSHOT.jar
  jib-maven-plugin/src/test/resources/webapp/final-name/WEB-INF/web.xml
Labels: cla: yes

#1098 Break up JibPluginIntegrationTest
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/DefaultTargetProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/EmptyProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/MultiProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
Labels: cla: yes

#1097 Add WAR integration test using Tomcat
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/build-tomcat.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/src/extra_js/bogus.js
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/src/extra_static/bogus.html
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/src/main/java/example/HelloWorld.java
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/src/main/resources/world
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/src/main/webapp/META-INF/MANIFEST.MF
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/src/main/webapp/WEB-INF/web.xml
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/src/main/webapp/index.html
Labels: cla: yes

#1102 Minor cleanups and fixes
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
Labels: cla: yes

#1106 Add WAR integration tests for exportDockerContext
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/HttpGetVerifier.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SkippedGoalVerifier.java
Labels: cla: yes

#1108 Add copyright header
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/HttpGetVerifier.java
Labels: cla: yes

#1076 Adds JibContainerBuilder#containerize.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/DockerDaemonImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/TarImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/TargetImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
  kokoro/presubmit.sh
  proposals/jib_core_library.md
Labels: cla: yes

#1101 Adds release scripts for Jib Core.
  jib-core/build.gradle
  jib-core/kokoro/release_build.sh
  jib-core/kokoro/release_publish.sh
  jib-core/kokoro/release_sign.sh
  jib-core/scripts/prepare_release.sh
Labels: cla: yes

#1112 Updates CHANGELOG for v0.9.12.
  jib-gradle-plugin/CHANGELOG.md
Labels: cla: yes

#1107 Include last modified time in cache selector digests instead of metadata
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LastModifiedTimeMetadata.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/UncompressedCacheWrite.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheEntryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageFilesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LastModifiedTimeMetadataTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
  jib-core/src/test/resources/cache/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tar.gz
  jib-core/src/test/resources/cache/metadata-v2.json
  jib-core/src/test/resources/cache/metadata-v3.json
  jib-core/src/test/resources/cache/metadata.json
Labels: cla: yes

#1116 Adds some more required parameters for Jib Core.
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageFormat.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
  proposals/jib_core_library.md
Labels: cla: yes

#1109 Adds container.user configuration
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/ContainerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
  jib-core/src/test/resources/json/containerconfig.json
  jib-core/src/test/resources/json/translated_ocimanifest.json
  jib-core/src/test/resources/json/translated_v22manifest.json
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
Labels: cla: yes

#1126 Adds JibContainerBuilder#setUser.
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
  proposals/jib_core_library.md
Labels: cla: yes

#1128 Remove unthrown exceptions
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/json/JsonTemplateMapperTest.java
Labels: cla: yes

#1129 Updates jib-core release script to accept version suffixes.
  jib-core/scripts/prepare_release.sh
  jib-maven-plugin/scripts/prepare_release.sh
Labels: cla: yes

#1131 Jib Core release v0.1.0
  jib-core/gradle.properties
Labels: cla: yes

#1119 Changes jib-gradle-plugin to use new Jib Core API.
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/NBuildStepsRunner.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTestHelper.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/NBuildStepsRunnerTest.java
Labels: cla: yes

#1124 Rename NBuildStepsRunner to BuildStepsRunner and remove original class
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/NBuildStepsRunner.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/NBuildStepsRunnerTest.java
Labels: cla: yes

#1133 Set file timestamps in image to epoch + 1 second
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1137 Update CHANGELOG
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1127 Add example of downloading and configuring the Stackdriver Debugger Java Agent
  examples/README.md
  examples/java-agent/README.md
  examples/java-agent/build.gradle
  examples/java-agent/gradle.properties
  examples/java-agent/gradle/wrapper/gradle-wrapper.jar
  examples/java-agent/gradle/wrapper/gradle-wrapper.properties
  examples/java-agent/gradlew
  examples/java-agent/gradlew.bat
  examples/java-agent/pom.xml
  examples/java-agent/src/main/java/example/HelloWorld.java
  examples/java-agent/src/main/resources/world
Labels: cla: yes

#1140 Update examples to use jib-gradle-plugin 0.9.12
  examples/helloworld/build.gradle
  examples/java-agent/build.gradle
  examples/micronaut/build.gradle
  examples/multi-module/build.gradle
  examples/spring-boot-draft/build.gradle
  examples/spring-boot-kubernetes/build.gradle
Labels: cla: yes

#1132 Allow using path or suffix in cred helper config
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Labels: cla: yes

#1117 Refactor layer construction code for Maven and Gradle
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelper.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java
  jib-plugins-common/src/test/resources/exploded-war/META-INF/context.xml
  jib-plugins-common/src/test/resources/exploded-war/Test.jsp
  jib-plugins-common/src/test/resources/exploded-war/WEB-INF/classes/HelloWorld.class
  jib-plugins-common/src/test/resources/exploded-war/WEB-INF/classes/package/Other.class
  jib-plugins-common/src/test/resources/exploded-war/WEB-INF/classes/package/test.properties
  jib-plugins-common/src/test/resources/exploded-war/WEB-INF/lib/dependency-1.0.0.jar
  jib-plugins-common/src/test/resources/exploded-war/WEB-INF/lib/dependencyX-1.0.0-SNAPSHOT.jar
  jib-plugins-common/src/test/resources/exploded-war/WEB-INF/web.xml
Labels: cla: yes

#1071 Inherit ENTRYPOINT and CMD from base image for WAR projects
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructorTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1141 Fix integration tests after #1071 (inheriting ENTRYPOINT and CMD)
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/war_servlet25/build-tomcat.gradle
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/resources/projects/war_servlet25/pom-tomcat.xml
Labels: cla: yes

#1144 Make Entrypoint parameter nullable
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/test/resources/webAppSampleDockerfile
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
Labels: cla: yes

#1145 Convert StepsRunnableConsumer to Runnable
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1148 Preliminary WAR support description in CHANGELOG / other fixes
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes, in progress

#1153 Maven release v0.9.13
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/pom.xml
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
Labels: cla: yes, in progress

#1159 Set tag to latest if version is unspecified in jibDockerBuild
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
Labels: cla: yes, in progress

#1162 Remove obsolete code
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
Labels: cla: yes, in progress

#1166 Add FilePermissions class
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/FilePermissions.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/FilePermissionsTest.java
Labels: cla: yes

#1156 Core changes for setting file permissions
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/FilePermissions.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/LayerConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/LayerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
Labels: cla: yes, in progress

#1170 Update commons-compress to 1.18
  jib-core/build.gradle
  jib-gradle-plugin/build.gradle
  jib-maven-plugin/pom.xml
  jib-plugins-common/build.gradle
Labels: cla: yes

#1176 Update CONTRIBUTING.md for style guide and jib-plugins-common
  CONTRIBUTING.md
Labels: cla: yes

#1171 Make CacheEntry extend Layer
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CachedLayer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCachedLayer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Layer.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCachedLayerTest.java
Labels: cla: yes

#1120 Add Travis build configuration
  .travis.yml
  build.sh
Labels: cla: yes

#1178 Update gradle extraDirectory config parameter to include path and permissions field
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtraDirectoryParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/resources/projects/multi-service/complex-service/build.gradle
  jib-gradle-plugin/src/test/resources/projects/simple/build.gradle
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelper.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java
Labels: cla: yes

#1187 Ignore file permissions in docker context integration test, add warning
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
Labels: cla: yes

#1182 Add file permissions to cache selector
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/FilePermissions.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
Labels: cla: yes

#1190 Remove LayerEntry#getAbsolute...String methods
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java
Labels: cla: yes

#1189 Remove dependence of filesTask on classes and assembly
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
Labels: cla: yes

#1195 Update maven extraDirectory config parameter to include path and permissions field
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojo.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoTest.java
  jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
  jib-maven-plugin/src/test/resources/projects/simple/pom.xml
  jib-maven-plugin/src/test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
  jib-maven-plugin/src/test/resources/projects/simple/src/main/jib-custom/bar/cat
  jib-maven-plugin/src/test/resources/projects/simple/src/main/jib-custom/foo
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelper.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Labels: cla: yes

#1160 Adds README for Jib Core.
  README.md
  jib-core/README.md
Labels: cla: yes, documentation, in progress, jib-core

#1155 Write out image digest to <target>/jib-image.digest
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildResult.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildResultTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/DefaultTargetProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/EmptyProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
Labels: cla: yes, in progress

#1163 Share PluginConfigurationProcessor between Gradle and Maven
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/AuthParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleRawConfigurationTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenRawConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/AppRootInvalidException.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/AuthProperty.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/InferredAuthRetrievalException.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes, in progress

#1197 Configuration refactoring idea
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTestHelper.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1207 Add jib-core changelog
  jib-core/CHANGELOG.md
Labels: cla: yes

#1210 Log inferred cred helper failure at info instead of warn
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
Labels: cla: yes

#1205 Share more code between tasks, Maven and Gradle
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes
