Repository GoogleContainerTools/jib, pull requests merged in 2018-06, with the labels that each got.

#343 Moves log output v2 proposal to archives.
  proposals/archives/docker_build.md
  proposals/archives/log_output_v2.md
  proposals/archives/maven_configuration_v2.md
Labels: proposal

#379 Initializes docs directory.
  docs/_config.yml
  docs/index.md
Labels: documentation

#380 Adds current README to docs for archiving.
  docs/README.md
  docs/index.md
  docs/v0.1.1/jib-gradle-plugin.md
  docs/v0.1.7/jib-maven-plugin.md
Labels: documentation

#386 Release 0.9.0
  jib-maven-plugin/pom.xml
Labels: jib-maven-plugin

#322 Updates README for beta release.
  README.md
  examples/helloworld/README.md
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: jib-gradle-plugin, jib-maven-plugin

#425 Adds compile to Maven one-liner and fixes project link.
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: documentation

#427 Add 'container' config to READMEs
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: PR: Not Ready, documentation

#466 Removes Azure container registry not supported limitation.
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: documentation

#469 Updates 0.9.0 version occurrences to v0.9.1.
  README.md
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: documentation
