Repository GoogleContainerTools/jib, pull requests merged in 2018-08, with the labels that each got.

#736 Adds multi-module example.
  examples/README.md
  examples/multi-module/.mvn/wrapper/MavenWrapperDownloader.java
  examples/multi-module/.mvn/wrapper/maven-wrapper.jar
  examples/multi-module/.mvn/wrapper/maven-wrapper.properties
  examples/multi-module/README.md
  examples/multi-module/build.gradle
  examples/multi-module/gradle-build.sh
  examples/multi-module/gradle/wrapper/gradle-wrapper.jar
  examples/multi-module/gradle/wrapper/gradle-wrapper.properties
  examples/multi-module/gradlew
  examples/multi-module/gradlew.bat
  examples/multi-module/hello-service/gradle.properties
  examples/multi-module/hello-service/pom.xml
  examples/multi-module/hello-service/src/main/java/hello/Application.java
  examples/multi-module/hello-service/src/main/java/hello/HelloController.java
  examples/multi-module/kubernetes.yaml
  examples/multi-module/maven-build.sh
  examples/multi-module/mvnw
  examples/multi-module/mvnw.cmd
  examples/multi-module/name-service/gradle.properties
  examples/multi-module/name-service/pom.xml
  examples/multi-module/name-service/src/main/java/name/Application.java
  examples/multi-module/name-service/src/main/java/name/NameController.java
  examples/multi-module/pom.xml
  examples/multi-module/settings.gradle
  jib-core/build.gradle
  jib-gradle-plugin/build.gradle
Labels: documentation

#786 Consolidates Maven- and GradleLayerConfigurations.
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
  jib-core/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
Labels: cla: yes

#805 Fix grammar in gradle plugin README.md
  jib-gradle-plugin/README.md
Labels: cla: yes

#811 Fix parsing auth block in maven plugin
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
Labels: cla: yes

#814 Add a comprehensive maven integration test
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/TestProject.java
  jib-maven-plugin/src/test/resources/projects/simple/auth/htpasswd
  jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
  jib-maven-plugin/src/test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
Labels: cla: yes

#816 Adds link to Velocity talk/slides.
  README.md
Labels: cla: yes

#820 Document adding extra files
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: cla: yes

#804 Passthrough labels from base image
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#770 Add FAQ entries for diagnosing connectivity issues
  CONTRIBUTING.md
  docs/faq.md
Labels: cla: yes

#818 Allow LocalRegistry to require credentials
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/Command.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/simple/auth/htpasswd
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/resources/projects/simple/auth/htpasswd
Labels: cla: yes

#822 Adds interface for CredentialRetriever.
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/CredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/Credentials.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/credentials/CredentialsTest.java
Labels: cla: yes

#821 Auto build gradle lib-project dependencies
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
Labels: cla: yes

#823 Adds list of CredentialRetrievers to BuildConfiguration.
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
Labels: cla: yes

#831 Add auth integration tests with different from/to registries and credentials
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
Labels: cla: yes

#824 Adds CredentialRetrieverFactory with initial one for Docker credential helpers.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/Credential.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/CredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Authorization.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/NonexistentDockerCredentialHelperException.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/NonexistentServerUrlDockerCredentialHelperException.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/credentials/CredentialTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigTest.java
Labels: cla: yes

#833 Disable mount+from
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
Labels: cla: yes

#825 Adds CredentialRetrieverFactory#inferCredentialHelper.
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
Labels: cla: yes

#837 Reduce duplicate code in build image integration tests
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
Labels: cla: yes

#828 Adds CredentialRetrieverFactory#dockerConfig.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/Credential.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Authorizations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigTest.java
  jib-core/src/test/resources/json/dockerconfig.json
  jib-core/src/test/resources/json/dockerconfig_index_docker_io_v1.json
Labels: cla: yes

#838 Fixes Base64 encoding to string.
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Authorizations.java
Labels: cla: yes

#842 Moves slf4j to test-compile only.
  jib-core/build.gradle
  jib-gradle-plugin/build.gradle
  jib-maven-plugin/pom.xml
Labels: cla: yes

#839 Makes list of credential retrievers.
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
Labels: cla: yes

#846 Add plugins-common to kokoro scripts
  kokoro/continuous.bat
  kokoro/continuous.sh
  kokoro/presubmit.bat
  kokoro/presubmit.sh
Labels: cla: yes

#847 Changes RetrieveRegistryCredentialsStep to use credential retrievers list.
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/CredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
Labels: cla: yes

#843 Change missing build output directory message
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
Labels: cla: yes

#857 Maven release v0.9.9
  jib-maven-plugin/pom.xml
Labels: cla: yes

#858 Gradle release v0.9.9
  jib-gradle-plugin/gradle.properties
Labels: cla: yes

#851 Removes setCredHelper, setKnownRegistryCredentials.
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleHelpfulSuggestionsBuilder.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/HelpfulSuggestionsProvider.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/HelpfulSuggestionsProvider.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenHelpfulSuggestionsBuilder.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestions.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestionsTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
Labels: cla: yes

#859 Fix xml comment in maven readme
  jib-maven-plugin/README.md
Labels: cla: yes

#861 Renames NonexistentDockerCredentialHelperException to DockerCredentialHelperNotFoundException.
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperNotFoundException.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
Labels: cla: yes

#860 Adds DefaultCredentialRetrievers to consolidate generation of CredentialRetrievers list.
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Labels: cla: yes

#862 Update version strings for 0.9.9
  CONTRIBUTING.md
  docs/faq.md
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  examples/multi-module/build.gradle
  examples/multi-module/pom.xml
  examples/spring-boot-draft/build.gradle
  examples/spring-boot-draft/pom.xml
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/README.md
Labels: cla: yes

#866 Add labels to gradle config
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/default-target/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/empty/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/simple/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
Labels: cla: yes

#867 Add labels to maven config
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/resources/projects/default-target/pom.xml
  jib-maven-plugin/src/test/resources/projects/empty/pom.xml
  jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
  jib-maven-plugin/src/test/resources/projects/simple/pom.xml
Labels: cla: yes

#455 Proposal RFC: Java Agents and More Layers
  proposals/archives/java_agents_and_more_layers.md
Labels: cla: yes, proposal

#869 Create new cache interfaces under a new package ncache.
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheReadEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheWriteEntry.java
Labels: cla: yes

#882 Update credential retrieval order
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Labels: cla: yes

#772 Adds entries for all directories in layer tarball.
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#888 Revert "Adds entries for all directories in layer tarball. (#772)"
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#883 Only warn if inferred credential helper threw NonexistentServerUrlDockerCredentialHelperException
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
Labels: cla: yes

#877 Write history as part of layer metadata
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/HistoryEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
  jib-core/src/test/resources/json/containerconfig.json
  jib-core/src/test/resources/json/translated_ocimanifest.json
  jib-core/src/test/resources/json/translated_v22manifest.json
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#896 Fixes CacheStorage interface and renames CacheReadEntry/CacheWriteEntry to CacheEntry/CacheWrite.
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheWrite.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheWrite.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheEntryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheWriteTest.java
Labels: cla: yes

#891 Adds entries for all directories in layer tarball.
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#880 Make sure to add assemble task dependencies after base plugin evaluation.
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/multiproject/a_packaged/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/multiproject/a_packaged/src/main/java/com/test/Empty.java
  jib-gradle-plugin/src/integration-test/resources/projects/multiproject/b_dependency/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/multiproject/b_dependency/src/main/java/com/test/Empty.java
  jib-gradle-plugin/src/integration-test/resources/projects/multiproject/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/multiproject/settings.gradle
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
Labels: cla: yes

#886 Note classpath difference with Gradle `run` task
  jib-gradle-plugin/CHANGELOG.md
Labels: cla: yes

#887 Enhance build.sh
  build.sh
Labels: cla: yes

#897 Adds FAQ about using debug base image.
  docs/faq.md
Labels: cla: yes

#899 Make createdBy in history configurable
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/HistoryEntry.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
Labels: cla: yes

#902 Propagate WorkingDir in container configuration
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
  jib-core/src/test/resources/json/containerconfig.json
  jib-core/src/test/resources/json/translated_ocimanifest.json
  jib-core/src/test/resources/json/translated_v22manifest.json
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#904 Some renaming and minor fixes
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
Labels: cla: yes

#893 Adds micronaut example.
  examples/helloworld/README.md
  examples/micronaut/README.md
  examples/micronaut/build.gradle
  examples/micronaut/dockerize-micronaut-jib.gif
  examples/micronaut/gradle/wrapper/gradle-wrapper.jar
  examples/micronaut/gradle/wrapper/gradle-wrapper.properties
  examples/micronaut/gradlew
  examples/micronaut/gradlew.bat
  examples/micronaut/settings.gradle
  examples/micronaut/src/main/groovy/example/micronaut/HelloController.groovy
  examples/micronaut/src/main/java/example/micronaut/Application.java
  examples/micronaut/src/main/resources/application.yml
  examples/micronaut/src/main/resources/logback.xml
  examples/micronaut/src/test/groovy/example/micronaut/HelloControllerSpec.groovy
  examples/multi-module/README.md
  examples/spring-boot-draft/README.md
Labels: cla: yes, documentation

#908 Eliminate Zip-Slip vulnerability
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ZipUtil.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ZipUtilTest.java
  jib-plugins-common/src/test/resources/test-archives/zip-slip-win.zip
  jib-plugins-common/src/test/resources/test-archives/zip-slip.zip
Labels: PR: Not Ready, cla: yes

#910 Adds link to Micronaut example.
  examples/README.md
Labels: cla: yes

#903 Remove DockerCredentialHelperFactory
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperFactory.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
Labels: cla: yes

#906 Add unzip util method
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ZipUtil.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ZipUtilTest.java
  jib-plugins-common/src/test/resources/test-archives/test.zip
  jib-plugins-common/src/test/resources/test-archives/zip-slip-win.zip
  jib-plugins-common/src/test/resources/test-archives/zip-slip.zip
Labels: cla: yes

#873 Add support for defining an entrypoint
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
Labels: cla: yes

#912 Log zip filename when blocking Zip-Slip
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ZipUtil.java
Labels: cla: yes

#915 Maven release v0.9.10
  jib-maven-plugin/pom.xml
Labels: cla: yes

#916 Gradle release v0.9.10
  jib-gradle-plugin/gradle.properties
Labels: cla: yes

#914 Use --password-stdin for docker login in integration tests instead of -p
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
Labels: cla: yes

#918 Update version strings for 0.9.10 release
  CONTRIBUTING.md
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  examples/micronaut/build.gradle
  examples/multi-module/build.gradle
  examples/multi-module/pom.xml
  examples/spring-boot-draft/build.gradle
  examples/spring-boot-draft/pom.xml
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/README.md
Labels: cla: yes

#895 Adds Spring Boot on Kubernetes example.
  examples/README.md
  examples/spring-boot-kubernetes/.mvn/wrapper/MavenWrapperDownloader.java
  examples/spring-boot-kubernetes/.mvn/wrapper/maven-wrapper.jar
  examples/spring-boot-kubernetes/.mvn/wrapper/maven-wrapper.properties
  examples/spring-boot-kubernetes/README.md
  examples/spring-boot-kubernetes/build.gradle
  examples/spring-boot-kubernetes/dockerize-spring-boot-jib.gif
  examples/spring-boot-kubernetes/gradle/wrapper/gradle-wrapper.jar
  examples/spring-boot-kubernetes/gradle/wrapper/gradle-wrapper.properties
  examples/spring-boot-kubernetes/gradlew
  examples/spring-boot-kubernetes/gradlew.bat
  examples/spring-boot-kubernetes/mvnw
  examples/spring-boot-kubernetes/mvnw.cmd
  examples/spring-boot-kubernetes/pom.xml
  examples/spring-boot-kubernetes/src/main/java/hello/Application.java
  examples/spring-boot-kubernetes/src/main/java/hello/HelloController.java
Labels: cla: yes, documentation

#911 Add skip parameter to base plugin configuration
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SkippedGoalVerifier.java
Labels: cla: yes
