Repository GoogleContainerTools/jib, pull requests merged in 2018-11, with the labels that each got.

#1218 Avoid creating directory in exploded-war build output directory in Ja…
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java
Labels: cla: yes

#1221 Disables Apache HTTP logging at registry client level.
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
Labels: cla: yes

#1214 Allow configuration docker executable path and additional environment variables
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/DockerDaemonImage.java
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/DockerDaemonImageTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerClientParameters.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Labels: cla: yes

#1223 CHANGELOG for jibDockerBuild.dockerClient params
  jib-gradle-plugin/CHANGELOG.md
Labels: cla: yes

#1228 Gradle release v0.10.0
  jib-gradle-plugin/gradle.properties
Labels: cla: yes

#1230 Maven release v0.10.0
  jib-maven-plugin/pom.xml
Labels: cla: yes

#1232 Fix wrong Maven build directory
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1233 Update version strings for 0.10.0
  CONTRIBUTING.md
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  examples/java-agent/build.gradle
  examples/java-agent/pom.xml
  examples/micronaut/build.gradle
  examples/multi-module/build.gradle
  examples/multi-module/pom.xml
  examples/spring-boot-draft/build.gradle
  examples/spring-boot-draft/pom.xml
  examples/spring-boot-kubernetes/build.gradle
  examples/spring-boot-kubernetes/pom.xml
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/README.md
Labels: cla: yes

#1174 maven-surefire-plugin 2.22.1
  jib-maven-plugin/pom.xml
Labels: cla: yes

#1147 Update README for 0.10.0
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: cla: yes, in progress

#1235 Update dependencies to use the 1.0.0 GA release of Micronaut
  examples/micronaut/build.gradle
Labels: cla: yes

#1215 Add volume support to jib-core.
  jib-core/CHANGELOG.md
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplate.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
  jib-core/src/test/resources/json/containerconfig.json
  jib-core/src/test/resources/json/translated_ocimanifest.json
  jib-core/src/test/resources/json/translated_v22manifest.json
Labels: cla: yes

#1236 Add DockerHealthCheck class
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/DockerHealthCheck.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/DockerHealthCheckTest.java
Labels: cla: yes

#1243 Define run.main for the main class to launch
  examples/micronaut/build.gradle
Labels: cla: yes

#1240 Eclipse Vert.x example
  examples/README.md
  examples/vertx/README.md
  examples/vertx/build.gradle
  examples/vertx/gradle/wrapper/gradle-wrapper.jar
  examples/vertx/gradle/wrapper/gradle-wrapper.properties
  examples/vertx/gradlew
  examples/vertx/gradlew.bat
  examples/vertx/settings.gradle
  examples/vertx/src/main/java/example/vertx/MainVerticle.java
  examples/vertx/src/main/resources/logback.xml
Labels: cla: yes, kokoro:run

#1244 Fix NullPointerException with incomplete auth config
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/AuthParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TargetImageParameters.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleRawConfigurationTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenRawConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/AuthProperty.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Labels: cla: yes

#1208 Adds initial style guide.
  CONTRIBUTING.md
  STYLE_GUIDE.md
Labels: cla: yes, documentation

#1260 Write out jib-image.id when image is built
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
Labels: cla: yes

#1264 Remove Docker context generator
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
  jib-core/src/test/resources/sampleDockerfile
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/MultiProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TestProject.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoTest.java
Labels: cla: yes

#1263 Allow inheriting ENTRYPOINT and CMD with INHERIT keyword
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
  jib-maven-plugin/CHANGELOG.md
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1278 Support for volumes on plugins
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/DefaultTargetProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/projects/simple/build.gradle
  jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/resources/projects/default-target/pom.xml
  jib-maven-plugin/src/test/resources/projects/empty/pom.xml
  jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
  jib-maven-plugin/src/test/resources/projects/simple/pom.xml
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/InvalidContainerVolumeException.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1285 Ensure Gradle dependency files exist
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
Labels: cla: yes

#1286 Propagate exposed ports and volumes from base image
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1287 Add FAQ entry for containerizing executable JAR
  docs/faq.md
Labels: cla: yes
