Repository GoogleContainerTools/jib, pull requests merged in 2019-05, with the labels that each got.

#1676 Add cache methods for retrieving manifest and container config
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheCorruptedException.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageFiles.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageReader.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ManifestAndConfig.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageFilesTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageReaderTest.java
Labels: cla: yes

#1680 Add content tests for image
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java
Labels: cla: yes

#1690 No generics for Image<> and ImageLayers<>
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildResult.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageTarball.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageLayers.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildResultTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/ImageTarballTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageLayersTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
Labels: cla: yes

#1686 Return absolute paths to extra directories
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2Test.java
  jib-maven-plugin/src/test/resources/maven/projects/multi/complex-service/pom.xml
Labels: cla: yes

#1688 Add FAQ when "401 Unauthorized" from registry
  docs/faq.md
Labels: cla: yes

#1687 Add offline mode to jib-core
  jib-core/CHANGELOG.md
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1692 Update CHANGELOG for multiple extra directories
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1689 Add offline mode to plugins
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1697 Add FAQ for Forbidden (DENIED) / expand FAQ / update error message
  docs/faq.md
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleHelpfulSuggestionsBuilder.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenHelpfulSuggestionsBuilder.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestions.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestionsTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunnerTest.java
Labels: cla: yes

#1678 Reorg and refactor code around Blob abuse
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/BlobDescriptor.java
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/FileBlob.java
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/InputStreamBlob.java
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/JsonBlob.java
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/StringBlob.java
  jib-core/src/main/java/com/google/cloud/tools/jib/blob/WritableContentsBlob.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildResult.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageWriter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageTarball.java
  jib-core/src/main/java/com/google/cloud/tools/jib/hash/CountingDigestOutputStream.java
  jib-core/src/main/java/com/google/cloud/tools/jib/hash/Digests.java
  jib-core/src/main/java/com/google/cloud/tools/jib/hash/WritableContents.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Request.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/json/JsonTemplateMapper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
  jib-core/src/test/java/com/google/cloud/tools/jib/blob/BlobTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageWriterTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/docker/json/DockerLoadManifestTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/hash/CountingDigestOutputStreamTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/http/TestBlobProgressListener.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/OCIManifestTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/V22ManifestTemplateTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/json/JsonTemplateMapperTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobCheckerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPullerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Labels: cla: yes

#1696 Fix lock file failures
  jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java
Labels: cla: yes

#1701 Core release v0.9.2
  jib-core/gradle.properties
Labels: cla: yes

#1700 Gradle release v1.2.0
  jib-gradle-plugin/gradle.properties
Labels: cla: yes

#1698 Maven release v1.2.0
  jib-maven-plugin/pom.xml
Labels: cla: yes

#1693 Update extra directories usage, merge after 1.2.0 release
  docs/index.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: PR: Merge After Release, cla: yes

#1675 Add extra classpath docs
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: PR: Merge After Release, cla: yes, documentation

#1699 No maven debug output
  jib-maven-plugin/scripts/prepare_release.sh
  kokoro/continuous.bat
  kokoro/continuous.sh
  kokoro/presubmit.bat
  kokoro/presubmit.sh
Labels: cla: yes

#1702 Update core version strings for 0.9.2
  jib-core/CHANGELOG.md
  jib-core/README.md
  jib-core/examples/build.gradle/README.md
Labels: cla: yes

#1703 Update plugin version strings for 1.2.0
  CONTRIBUTING.md
  examples/dropwizard/pom.xml
  examples/helloworld/build.gradle
  examples/helloworld/pom.xml
  examples/java-agent/build.gradle
  examples/java-agent/pom.xml
  examples/ktor/build.gradle.kts
  examples/micronaut/build.gradle
  examples/multi-module/build.gradle
  examples/multi-module/pom.xml
  examples/spring-boot/build.gradle
  examples/spring-boot/pom.xml
  examples/vertx/build.gradle
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/README.md
Labels: cla: yes

#1705 Fix maven changelog
  jib-maven-plugin/CHANGELOG.md
Labels: cla: yes

#1704 Use Docker config.json credential retrievers before inferred retrievers
  jib-gradle-plugin/CHANGELOG.md
  jib-maven-plugin/CHANGELOG.md
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Labels: cla: yes

#1707 Better error message for registries not supporting OCI manifest push
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Labels: cla: yes

#1714 Add version to skaffold-files-v2 output
  jib-core/src/main/java/com/google/cloud/tools/jib/ProjectInfo.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutput.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutputTest.java
Labels: cla: yes

#1715 Use `jib.containerize` property to only containerize specific module/project
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SkippedGoalVerifier.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
Labels: cla: yes

#1712 Evaluate settings.xml later, and per id
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DecryptedMavenSettings.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProvider.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DecryptedMavenSettingsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProviderTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/ProxyProviderTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SettingsFixture.java
  jib-maven-plugin/src/test/resources/maven/settings/bad-encrypted-proxy-settings.xml
  jib-maven-plugin/src/test/resources/maven/settings/encrypted-proxy-settings.xml
  jib-maven-plugin/src/test/resources/maven/settings/http-only-proxy-settings.xml
  jib-maven-plugin/src/test/resources/maven/settings/https-only-proxy-settings.xml
  jib-maven-plugin/src/test/resources/maven/settings/no-active-proxy-settings.xml
  jib-maven-plugin/src/test/resources/maven/settings/readme
  jib-maven-plugin/src/test/resources/maven/settings/settings-security.empty.xml
  jib-maven-plugin/src/test/resources/maven/settings/settings-security.xml
  jib-maven-plugin/src/test/resources/maven/settings/settings.xml
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/InferredAuthException.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/InferredAuthProvider.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Labels: cla: yes

#1717 Remove RegistryAuthenticator.Initializer
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
Labels: cla: yes

#1684 Reorg and refactor repo - continued
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildResult.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ThrottledProgressEventDispatcherWrapper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageWriter.java
  jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageTarball.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/ThrottledAccumulatingConsumer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/hash/CountingDigestOutputStream.java
  jib-core/src/main/java/com/google/cloud/tools/jib/hash/Digests.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Authorization.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Authorizations.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/BlobHttpContent.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/BlobProgressListener.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/ListenableCountingOutputStream.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/NotifyingOutputStream.java
  jib-core/src/main/java/com/google/cloud/tools/jib/http/Response.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/json/JsonTemplateMapper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPuller.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPuller.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
  jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageReaderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/hash/CountingDigestOutputStreamTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/http/ConnectionTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/http/NotifyingOutputStreamTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/http/ResponseTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/http/TestBlobProgressListener.java
  jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPullerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPusherTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPullerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
Labels: cla: yes

#1723 Fix groupId in docs.
  jib-maven-plugin/README.md
Labels: cla: yes

#1726 Make Containerizer EventHandlers non optional
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/EventHandlers.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
Labels: cla: yes

#1720 Refactor progress completion reporting
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/AllocationCompletionTracker.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandler.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/AllocationCompletionTrackerTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ProgressDisplayGenerator.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/ProgressDisplayGeneratorTest.java
Labels: cla: yes

#1729 Adjust MainClassFinder api
  jib-core/CHANGELOG.md
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/MainClassFinder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/MainClassFinderTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
Labels: cla: yes

#1735 Update jackson-databind to 2.9.9
  jib-core/build.gradle
  jib-gradle-plugin/build.gradle
  jib-maven-plugin/pom.xml
  jib-plugins-common/build.gradle
Labels: cla: yes

#1738 Document symlink behaviour for extras
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: cla: yes

#1733 Move ImageFormat to api package
  jib-core/src/main/java/com/google/cloud/tools/jib/api/ImageFormat.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
Labels: cla: yes

#1741 Include pointers to FAQ diagnostic answers in new-issue template
  .github/ISSUE_TEMPLATE.md
Labels: cla: yes

#1736 Move LayerConfiguration and LayerEntry to api package
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerEntry.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
  jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java
  jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
  jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JavaContainerBuilderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/LayerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelperTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1749 Remove JibEventType
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/EventHandlers.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEventType.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/TimerEventDispatcherTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/EventHandlersTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/events/LogEventTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/events/ProgressEventTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandlerTest.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1750 Rename ExposedPortsParser to Ports
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/Ports.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/PortsTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Labels: cla: yes

#1751 Remove JavaEntrypointConstructor
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
  jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java
  jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructorTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Labels: cla: yes

#1752 No need to pass appRoot when instantiate ProjectProperties
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
  jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
  jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Labels: cla: yes

#1753 Prevent LayerEntry backreach into LayerConfiguration
  jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerEntry.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/LayerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
Labels: cla: yes

#1744 Remove informative BuildStepType from events
  jib-core/README.md
  jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildStepType.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayersStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ThrottledProgressEventDispatcherWrapper.java
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/events/LayerCountEvent.java
  jib-core/src/main/java/com/google/cloud/tools/jib/event/events/ProgressEvent.java
  jib-core/src/test/java/com/google/cloud/tools/jib/api/LayerConfigurationTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcherTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/events/ProgressEventTest.java
  jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandlerTest.java
Labels: cla: yes
