Repository GoogleContainerTools/jib, pull requests merged in 2021-11, with the labels that each got.

#3491 Change default base images from AdoptOpenJDK to Eclipse Adoptium Eclipse Temurin (for Java 8 and 11) and use Azul Zulu (for Java 17)
  jib-cli/CHANGELOG.md
  jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ArtifactProcessors.java
  jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/ArtifactProcessorsTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JibCliTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarFilesTest.java
  jib-cli/src/test/resources/jar/java14WithModuleInfo.jar
  jib-cli/src/test/resources/jar/java18.jar
  jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
  jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
  jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-java17.gradle
  jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/IncompatibleBaseImageJavaVersionException.java
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
  proposals/buildfile.md
  proposals/container-build-plan-spec.md
Labels: cla: yes

#3497 Clean up build.gradle
  build.gradle
Labels: cla: yes

#3496 Refactor tests
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/BuildTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/CredentialsTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/WarTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpecTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java
  jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpecTest.java
Labels: cla: yes

#3499 Add FAQ about unsupported Java version and throw error with more helpful message
  docs/faq.md
  jib-core/src/main/java/com/google/cloud/tools/jib/api/MainClassFinder.java
Labels: cla: yes

#3503 Jib CLI 0.8.0 post-release updates
  jib-cli/CHANGELOG.md
  jib-cli/README.md
Labels: kokoro:run, cla: yes

#3504 Update CLI post-release checklist
  .github/RELEASE_TEMPLATES/cli_release_checklist.md
Labels: cla: yes

#3501 CLI release v0.8.0
  jib-cli/gradle.properties
Labels: cla: yes, PR: Merge After Release

#3500 Add enabling container registry FAQ answer
  docs/faq.md
Labels: cla: yes

#3512 Mention that JAVA_TOOL_OPTIONS only support a max of 1024 chars
  docs/faq.md
Labels: cla: yes
