Repository GoogleContainerTools/jib, pull requests merged in 2022-01, with the labels that each got.

#3532 Also looks for registry credential files in XDG folders
  docs/faq.md
  jib-gradle-plugin/CHANGELOG.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/CHANGELOG.md
  jib-maven-plugin/README.md
  jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
  jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Labels: p3, discuss

#3498 Doc updates for Jib plugin 3.2 and Jib CLI 0.8 releases
  README.md
  docs/default_base_image.md
  docs/faq.md
  jib-gradle-plugin/README.md
  jib-maven-plugin/README.md
Labels: cla: yes, PR: Merge After Release

#3556 gradle release v3.2.0
  jib-gradle-plugin/gradle.properties
Labels: PR: Merge After Release

#3558 maven release v3.2.0
  jib-maven-plugin/gradle.properties
Labels: PR: Merge After Release

#3554 CLI release v0.9.0
  jib-cli/gradle.properties
Labels: PR: Merge After Release
